# Generated by Django 5.1.2 on 2024-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DR', 'Driver'), ('PA', 'Passenger')], max_length=2),
        ),
    ]
