# Generated by Django 5.1.2 on 2024-11-09 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_user_car_users'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.AddField(
            model_name='trips',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='cars.car'),
            preserve_default=False,
        ),
    ]
