# Generated by Django 5.1.2 on 2024-11-10 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trips_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='users',
            field=models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
