# Generated by Django 5.1.2 on 2024-11-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_frozenpassenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='car',
        ),
    ]
