# Generated by Django 5.1.2 on 2024-11-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_user'),
        ('trips', '0006_remove_trips_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='cars.car'),
            preserve_default=False,
        ),
    ]
